[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "roadqa_imu"
version = "0.0.1"
dependencies = [
    "numpy",
    "matplotlib",
    "folium",
    "scipy",
]

[tool.setuptools]
packages = ["roadqa_imu"]